# Generated by Django 5.1.4 on 2025-01-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_post_options_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='com',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.post'),
        ),
    ]
