# Generated by Django 5.1.4 on 2025-01-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_remove_post_com_comment_author_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCode',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
    ]
