# Generated by Django 5.1.4 on 2025-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_delete_emailcode_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Танк', 'Танк'), ('Хил', 'Хил'), ('ДД', 'ДД'), ('Торговец', 'Торговец'), ('Гильдмастер', 'Гильдмастер'), ('Квестгивер', 'Квестгивер'), ('Кузнец', 'Кузнец'), ('Кожевник', 'Кожевник'), ('Алхимик', 'Алхимик'), ('Мастер магии', 'Мастер магии')], max_length=50),
        ),
    ]
